apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: apps
  annotations:
    client.lifecycle.config.k8s.io/mutation: ignore
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.28.0
        ports:
        - containerPort: 80
