kind: Pod
apiVersion: v1
metadata:
  name: test
  namespace: mutation-test
spec:
  containers:
    - name: nginx
      image: docker.io/nginx:latest
      ports:
        - name: http
          containerPort: 80
