apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: mutation-test
  annotations:
    client.lifecycle.config.k8s.io/mutation: ignore
    config.kubernetes.io/apply-time-mutation: |
      - sourceRef:
          kind: Pod
          name: test
          namespace: mutation-test
        sourcePath: $.status.podIP
        targetPath: $.stringData.foo
stringData:
  foo: VALUE2
